steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "mkdocs-material","&&", "mkdcos","build"]
artifacts:
  objects:
    location: gs://scala.dev
    paths: ['site']
