steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "mkdocs-material"]
  - name: python
    entrypoint: mkdocs
    args: ["build"]
artifacts:
  objects:
    location: gs://scala.dev
    paths: ['site']
